packages:
  - apps/*
  - packages/*
catalog:
  "@types/react": ^19.2.10
  "@types/react-dom": ^19.2.3
  better-auth: 1.5.2
  dotenv: ^17.4.2
  lucide-react: ^0.546.0
  next-themes: ^0.4.6
  react: ^19.2.3
  react-dom: ^19.2.3
  sonner: ^2.0.5
  tailwindcss: ^4.1.18
  zod: 4.3.6
overrides:
  "@hono/node-server@<1.19.13": ">=1.19.13"
  axios@>=1.0.0 <1.15.0: ">=1.15.0"
  brace-expansion@>=4.0.0 <5.0.5: ">=5.0.5"
  defu@<=6.1.4: ">=6.1.5"
  drizzle-orm@<0.45.2: ">=0.45.2"
  effect@<3.20.0: ">=3.20.0"
  esbuild@<=0.24.2: ">=0.25.0"
  fast-xml-parser@>=4.0.0-beta.3 <=5.5.6: ">=5.5.7"
  fast-xml-parser@>=5.0.0 <5.5.6: ">=5.5.6"
  follow-redirects@<=1.15.11: ">=1.16.0"
  hono@<4.11.10: ">=4.11.10"
  hono@<4.11.7: ">=4.11.7"
  hono@<4.12.14: ">=4.12.14"
  hono@<4.12.4: ">=4.12.4"
  hono@<4.12.7: ">=4.12.7"
  kysely@<=0.28.13: ">=0.28.14"
  kysely@>=0.26.0 <=0.28.11: ">=0.28.12"
  lodash@>=4.0.0 <=4.17.22: ">=4.17.23"
  micromatch@4.0.8>picomatch: 4.0.4
  next@>=16.0.0-beta.0 <16.2.3: ">=16.2.3"
  next@>=16.0.1 <16.2.3: ">=16.2.3"
  path-to-regexp@>=8.0.0 <8.4.0: ">=8.4.0"
  picomatch@<2.3.2: ">=2.3.2"
  picomatch@>=4.0.0 <4.0.4: ">=4.0.4"
